language: ruby
rvm:
  - 2.5.3

services:
  - redis-server

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - CC_TEST_REPORTER_ID=2fcb230ef397cb43c693b113105b17ca39a3a65ac5093ca3096cbf6a3c0f1a98

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
 email:
    - maximiliano.colombo@wolox.com.ar

cache:
  bundler: true
