language: ruby
rvm:
  - 2.2.0

addons:
  code_climate:
    repo_token: 2fcb230ef397cb43c693b113105b17ca39a3a65ac5093ca3096cbf6a3c0f1a98

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

notifications:
 email:
    - maximiliano.colombo@wolox.com.ar

cache:
  bundler: true
